name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Backend
      - name: Install backend dependencies
        run: npm install
      - name: Lint backend
        run: npm run lint
      - name: Test backend
        run: npm run test
      - name: Build backend
        run: npm run tsc

      # Frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2
      - name: Trigger deployment
        if: >
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '#skip')
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_URL }}"
      - name: Notify on success
        if: > 
          success() && 
          github.event_name == 'push' && 
          !contains(github.event.head_commit.message, '#skip')
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Full Stack Patientor"
          content: "A new version of Patientor deployed"
          embed-title: "Success"
          embed-description: A new version of Patientor deployed to ${{ secrets.DEPLOYMENT_URL }}.
          embed-footer-text: "Severity: Informational"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-color: 3066993
      - name: Notify on failure
        if: failure()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Full Stack Patientor"
          content: "Patientor deployment failed"
          embed-title: "Error"
          embed-description: A commit [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) by **${{ github.actor }}** broke the build.
          embed-footer-text: "Severity: Error"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-color: 15158332

  tag_release:
    needs: [deployment_pipeline]
    if: >
      github.event_name == 'push' &&
      !contains(github.event.head_commit.message, '#skip')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
