name: Health Check

on:
  #schedule:
    #- cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check_service:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URLs
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.DEPLOYMENT_URL }}ping
          follow-redirect: false 
          max-attempts: 3            
          retry-delay: 5s             
          retry-all: false
